# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20170203_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbboards',
            name='amps',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='android',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='audio_in',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='audio_out',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='bluetooth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='board_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='clock',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='cpu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='cvbs',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='display',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='ethernet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='gpu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='hdmi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='interfaces',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='ir',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='ram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='rating',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='sata',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='sd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='soc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='storage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='temp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='usb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='usb_otg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='vga',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='volts',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='wake_on_lan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='weight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='wifi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbboards',
            name='windows',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
