# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20170203_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbboards',
            name='board_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
